### ISSUE TITLE
Predicitons for current_week+2

### ISSUE THREAD

**Issue by qamaheshkumar** [JoshuaPlacidi/FPL-Predictions#1]
Hi,

The models predictions is working as explained for history data. But when tried for futuristic data it resulted in zeros.

Example :1: This worked fine
gw = 40
predicted_points, real_points, cost = select(gw,all_predictions,True)

Example:2: Resulted in zeros:
gw = 41
predicted_points, real_points, cost = select(gw,all_predictions,True)

**Comment by JoshuaPlacidi** [comment]
Hi, this project was made during the suspended season of 19/20 so the data is outdated by now. In order to make `select()` work on this new season (20/21) you will need to update  `player_data.csv` and then run that through the predictions pipeline.

To generate predictions for future games you will need to add entries to `player_data.csv` manually with these columns:
`GW,player_id,position,first_name,second_name,team_code,opp_diff,was_home,value,season`

You can leave unknown stats such as minutes and points as 0 for now but should update them when the game has been played. You will then need to run the rolling_df function which will calculate all the `_sum` columns from the previous 3 played games: `minutes_sum,bps_sum,influence_sum,threat_sum,ict_sum,creat_sum,yel_sum,red_sum,selected_by,tran_sum,goals_sum,assists_sum,points_sum,saves_sum,goals_con_sum,clean_sheets_sum`

Once `player_data.csv` has been updated you can then run it through the predictions notebook to forecast points for the added entries and then run that in `select()` function to get a predicted team.

As you can see this project wasn't designed to easily accumulate more data and make future predictions but if you wished too those are the steps you would need to take. I am currently in the early stages of remaking this repo to be much more accessible and more accurate.
